FROM node:16-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY example-frontend/ ./

RUN npm install \
    && npm install -g serve \
    && npm run build \
    && adduser -D server

USER server

CMD ["serve", "-s", "-l", "5000", "build"]
