name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release NodeJS app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: frensing/express-app:latest
          context: ./part3/e3.01/express-app/
