version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  frontend:
    image: example-frontend:e1.14
    ports:
      - "5000:5000"
      
  backend:
    image: example-backend:e1.14
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
  
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
